version: "2"

services:

  grafana:
    image: grafana/grafana:6.1.6
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: on-failure

  influxdb:
    image: influxdb:1.7.6-alpine
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: on-failure

  mosquitto:
    image: eclipse-mosquitto:1.6.2
    ports:
      - 1883:1883
      - 9001:9001
    restart: on-failure

volumes:
  grafana-storage:
  influxdb-storage:
