{
 "title": "Lego Boost Guitar",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Played Colors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "BLUE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "color",
     "query": "SELECT sum(\"value\") FROM \"color\" WHERE (\"color\" = 'BLUE') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "color", "operator": "=", "value": "BLUE" }
     ]
    },
    {
     "alias": "CYAN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "color",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "color", "operator": "=", "value": "CYAN" }
     ]
    },
    {
     "alias": "RED",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "color",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "color", "operator": "=", "value": "RED" }
     ]
    },
    {
     "alias": "YELLOW",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "color",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "color", "operator": "=", "value": "YELLOW" }
     ]
    }
   ]
  },
  {
   "title": "Tire",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "motor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "motor", "operator": "=", "value": "B" }
     ]
    }
   ]
  },
  {
   "title": "Handle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "motor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "motor", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "Current Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "query": "SELECT max(\"value\") FROM \"voltage\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bumps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bump",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "query": "SELECT max(\"value\") FROM \"voltage\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  }
 ]
}